lecteurcarte.o: lecteurcarte.cpp lecteurcarte.h voyants.h timer.h \
 baseclient.h prise.h boutons.h generateur_save.h
baseclient.o: baseclient.cpp baseclient.h voyants.h timer.h prise.h \
 lecteurcarte.h boutons.h generateur_save.h
timer.o: timer.cpp timer.h
boutons.o: boutons.cpp boutons.h
voyants.o: voyants.cpp voyants.h timer.h
prise.o: prise.cpp prise.h
generateur_save.o: generateur_save.cpp generateur_save.h prise.h \
 boutons.h baseclient.h voyants.h timer.h lecteurcarte.h
borne.o: borne.cpp lecteurcarte.h voyants.h timer.h baseclient.h prise.h \
 boutons.h generateur_save.h
